


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN T9 [get_ports rst_n]
set_property PACKAGE_PIN D4 [get_ports clk]

set_property PACKAGE_PIN A7 [get_ports {ad_data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_data_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sample_data_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad_busy]
set_property IOSTANDARD LVCMOS33 [get_ports ad_convst]
set_property IOSTANDARD LVCMOS33 [get_ports ad_cs]
set_property IOSTANDARD LVCMOS33 [get_ports ad_rd]
set_property IOSTANDARD LVCMOS33 [get_ports ad_reset]
set_property IOSTANDARD LVCMOS33 [get_ports sample_valid]
set_property PACKAGE_PIN A5 [get_ports {ad_data_in[1]}]
set_property PACKAGE_PIN E5 [get_ports {ad_data_in[2]}]
set_property PACKAGE_PIN B7 [get_ports {ad_data_in[3]}]
set_property PACKAGE_PIN D6 [get_ports {ad_data_in[4]}]
set_property PACKAGE_PIN C4 [get_ports {ad_data_in[5]}]
set_property PACKAGE_PIN E6 [get_ports {ad_data_in[6]}]
set_property PACKAGE_PIN D5 [get_ports {ad_data_in[7]}]
set_property PACKAGE_PIN D8 [get_ports {ad_data_in[8]}]
set_property PACKAGE_PIN C6 [get_ports {ad_data_in[9]}]
set_property PACKAGE_PIN C9 [get_ports {ad_data_in[10]}]
set_property PACKAGE_PIN C7 [get_ports {ad_data_in[11]}]
set_property PACKAGE_PIN A8 [get_ports {ad_data_in[12]}]
set_property PACKAGE_PIN D9 [get_ports {ad_data_in[13]}]
set_property PACKAGE_PIN C8 [get_ports {ad_data_in[14]}]
set_property PACKAGE_PIN D10 [get_ports {ad_data_in[15]}]
set_property PACKAGE_PIN A4 [get_ports ad_busy]
set_property PACKAGE_PIN B4 [get_ports ad_convst]
set_property PACKAGE_PIN B6 [get_ports ad_cs]
set_property PACKAGE_PIN D3 [get_ports ad_rd]
set_property PACKAGE_PIN B5 [get_ports ad_reset]
set_property PACKAGE_PIN P9 [get_ports sample_valid]
set_property PACKAGE_PIN A15 [get_ports {sample_data_out[15]}]
set_property PACKAGE_PIN C16 [get_ports {sample_data_out[14]}]
set_property PACKAGE_PIN B16 [get_ports {sample_data_out[13]}]
set_property PACKAGE_PIN C11 [get_ports {sample_data_out[12]}]
set_property PACKAGE_PIN C12 [get_ports {sample_data_out[11]}]
set_property PACKAGE_PIN D13 [get_ports {sample_data_out[10]}]
set_property PACKAGE_PIN C13 [get_ports {sample_data_out[9]}]
set_property PACKAGE_PIN E12 [get_ports {sample_data_out[8]}]
set_property PACKAGE_PIN E13 [get_ports {sample_data_out[7]}]
set_property PACKAGE_PIN E11 [get_ports {sample_data_out[6]}]
set_property PACKAGE_PIN D11 [get_ports {sample_data_out[5]}]
set_property PACKAGE_PIN D14 [get_ports {sample_data_out[4]}]
set_property PACKAGE_PIN D15 [get_ports {sample_data_out[3]}]
set_property PACKAGE_PIN F12 [get_ports {sample_data_out[2]}]
set_property PACKAGE_PIN F13 [get_ports {sample_data_out[1]}]
set_property PACKAGE_PIN E16 [get_ports {sample_data_out[0]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {sample_data_out_OBUF[0]} {sample_data_out_OBUF[1]} {sample_data_out_OBUF[2]} {sample_data_out_OBUF[3]} {sample_data_out_OBUF[4]} {sample_data_out_OBUF[5]} {sample_data_out_OBUF[6]} {sample_data_out_OBUF[7]} {sample_data_out_OBUF[8]} {sample_data_out_OBUF[9]} {sample_data_out_OBUF[10]} {sample_data_out_OBUF[11]} {sample_data_out_OBUF[12]} {sample_data_out_OBUF[13]} {sample_data_out_OBUF[14]} {sample_data_out_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ad_data_in_IBUF[0]} {ad_data_in_IBUF[1]} {ad_data_in_IBUF[2]} {ad_data_in_IBUF[3]} {ad_data_in_IBUF[4]} {ad_data_in_IBUF[5]} {ad_data_in_IBUF[6]} {ad_data_in_IBUF[7]} {ad_data_in_IBUF[8]} {ad_data_in_IBUF[9]} {ad_data_in_IBUF[10]} {ad_data_in_IBUF[11]} {ad_data_in_IBUF[12]} {ad_data_in_IBUF[13]} {ad_data_in_IBUF[14]} {ad_data_in_IBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {state[0]} {state[1]} {state[2]} {state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list ad_cs_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list ad_rd_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list sample_valid_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
